name = "exec-os-api"
main = "src/api/index.ts"
compatibility_date = "2024-06-09"

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "exec-os-db"
database_id = ""

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = ""

# Environment variables
[vars]
NODE_ENV = "development"

# Build configuration
[build]
command = "pnpm build:api"

# Routes
[[routes]]
pattern = "/api/*"
zone_name = ""